project-codeflare/rayvens

- examples/slack/slack_operator_mode.py
- rayvens/core/common.py
- rayvens/core/kamel.py
- rayvens/core/operator.py
- rayvens/core/ray_serve.py
Add readiness probe to await start.
> Add readiness probe to await start

- docs/connectors.md
Update documentation for Cloud Object Storage source.
> Update documentation for Cloud Object Storage source

- scripts/rayvens-setup.sh
Improve setup script with python project installation on cluster.
> Add python project installation on cluster to script

- scripts/rayvens-setup.sh
Fix use pip for pip dependencies.
> Fix use pip for pip dependencies

- examples/datasets/file_source_to_dataset.py
- examples/datasets/file_source_to_dataset_actor.py
- examples/datasets/test_files/test.txt
- examples/file/file_source.py
- rayvens/core/FileWatchQueue.java
- rayvens/core/kamel.py
Event triggered Ray datasets examples.
> Add examples with event triggered Ray datasets

- docs/connectors.md
Add documentation changes for file watch source
> Add documentation changes for file watch source

- rayvens/core/kamel.py
Enable port randomization for all transport types.
> Enable port randomization for all transport types

- rayvens/api.py
> Remove unused field

- rayvens/api.py
Limit subscribers for scaled Kafka streams
> Limit subscribers for scaled Kafka streams

- rayvens/core/invocation.py
> Add timeout to log check

- rayvens/api.py
- rayvens/core/common.py
- rayvens/core/integration.py
- rayvens/core/kafka.py
- rayvens/core/local.py
- rayvens/core/mode.py
- rayvens/core/operator.py
- rayvens/core/ray_serve.py
- rayvens/core/utils.py
Check port is available by default.
Introduce port check flag to disable the check on demand:
```
rayvens.init(..., check_port=False)
```
> Check port is available

- examples/kafka/kafka_event_streaming.py
- rayvens/core/catalog.py
Add scaling kafka transport example.
> Add scaling kafka transport example

- examples/blogs/binance_to_slack.py
> Add folder for blog examples

- examples/kafka/kafka_event_streaming_source.py
- rayvens/api.py
- rayvens/core/common.py
- rayvens/core/operator_kafka.py
Enable Kafka transport for operator mode.
> Enable Kafka transport for operator mode

- rayvens/core/common.py
- rayvens/core/local.py
Use readiness probe in local mode.
> Use readiness probe in local mode

- rayvens/core/common.py
- rayvens/core/integration.py
- rayvens/core/kafka.py
- rayvens/core/local.py
- rayvens/core/operator.py
- rayvens/core/operator_kafka.py
Gracefully end source-related threads.
> Gracefully end source-related threads

- rayvens/core/common.py
- rayvens/core/invocation.py
Increase logging timer to 5 minutes.
> Increase logging and readiness timeouts

- rayvens/core/invocation.py
- rayvens/core/utils.py
> Fix kamel log check

- rayvens/cli/README.md
- rayvens/cli/__init__.py
- rayvens/cli/build.py
- rayvens/cli/delete.py
- rayvens/cli/docker.py
- rayvens/cli/examples/build-base-image.sh
- rayvens/cli/examples/build-slack-sink-image.sh
- rayvens/cli/examples/delete-slack-sink-local.sh
- rayvens/cli/examples/run-slack-sink-local.sh
- rayvens/cli/file.py
- rayvens/cli/files.py
- rayvens/cli/java.py
- rayvens/cli/kamel.py
- rayvens/cli/kubernetes.py
- rayvens/cli/rayvens_print.py
- rayvens/cli/rayvens_setup.py
- rayvens/cli/run.py
- rayvens/cli/utils.py
- rayvens/cli/version.py
- rayvens/core/catalog.py
- rayvens/core/catalog_utils.py
- rayvens/core/common.py
- rayvens/core/invocation.py
- rayvens/core/kamel.py
- rayvens/core/kubernetes.py
- rayvens/rayvens
- rayvens/rayvens_cli.py
- setup.py
> Add Rayvens CLI

- rayvens/cli/delete.py
- rayvens/cli/kubernetes.py
- rayvens/cli/run.py
- rayvens/core/integration.py
- rayvens/core/utils.py
Add create, exists and delete methods for Kubernetes entities.
> Add create, exists and delete methods for Kubernetes entities

- examples/multitask/multitask.py
- rayvens/api.py
- rayvens/core/integration.py
Add support for multi task operators and stream context.
> Add support for multi task operators and stream context

- examples/cloud_object_storage/cos_sink.py
- rayvens/__init__.py
- rayvens/core/catalog.py
- rayvens/core/common.py
Add support for header passing to sinks
> Add support for header passing to sinks

- examples/batching/batching.py
- examples/batching/batching_source.py
- examples/batching/batching_with_multitask.py
- rayvens/api.py
- rayvens/core/common.py
> Add event stream batching

- examples/cloud_object_storage/cos_sink_multitask.py
Add cloud object storage sink and multitask operator example
> Add cloud object storage sink and multitask operator example

- scripts/rayvens-setup.sh
> Add missing comma

- rayvens/core/catalog.py
allow AWS integration by optioning endpoint-url and adding RAW() to render key creds
> endpoint-url optional and RAW creds

- scripts/rayvens-setup.sh
also added project-mount / max-worker params
> change setup script logic

- Dockerfile
- Dockerfile.release
- README.md
- scripts/cluster.yaml
- scripts/rayvens-setup.sh
Update Rayvens to version 0.5.0 and Ray to version 1.12.1
> Update Rayvens to version 0.5.0 and Ray to version 1.12.1

- docs/connectors.md
change source_config for file-source-raw
> change source_config for file-source-raw
